---
- hosts: localhost
  collections:
    - kubernetes.core
  tasks:
  - name: Location Label Assign Metadata
    k8s:
      state: present
      definition:
        apiVersion: mutations.gatekeeper.sh/v1alpha1
        kind: AssignMetadata
        metadata:
          name: gatekeeperassignlocation
        spec:
          match:
            scope: Namespaced
          location: "metadata.labels.location"
          parameters:
            assign:
              value: "eastern"
