---
- hosts: localhost
  collections:
    - kubernetes.core
  tasks:
  - name: Namespace Label Constraint Template
    k8s:
      state: present
      definition:
        apiVersion: templates.gatekeeper.sh/v1beta1
        kind: ConstraintTemplate
        metadata:
          name: namespace-must-have-label
        spec:
          crd:
            spec:
              names:
                kind: namespace-must-have-label
              validation:
                # Schema for the `parameters` field
                openAPIV3Schema:
                  properties:
                    labels:
                      type: array
                      items: string
          targets:
            - target: admission.k8s.gatekeeper.sh
              rego: |
                package k8srequiredlabels

                violation[{"msg": msg, "details": {"missing_labels": missing}}] {
                  provided := {label | input.review.object.metadata.labels[label]}
                  required := {label | label := input.parameters.labels[_]}
                  ns := input.review.object.metadata.namespace
                  missing := required - provided
                  count(missing) > 0
                  msg := sprintf("you must provide labels in namespace \"%s\": %v", [ns, missing])
                }
  - name: Namespace Label Constraint
    k8s:
      state: present
      definition:
        apiVersion: constraints.gatekeeper.sh/v1beta1
        kind: namespace-must-have-label
        metadata:
          name: namespace-must-have-label
        spec:
          enforcementAction: warn
          match:
            kinds:
              - apiGroups: [""]
                kinds: ["Namespace"]
          parameters:
            labels: ["gatekeeper"]
